#!/bin/bash
# upgradeall
# Upgrade Software both through Pacman & Yay

# Upgrade Arch Packages
upgrade_pacman() {
	echo "Upgrade Arch Packages"

	sudo pacman -Syu

	if [ $? -eq 0 ]; then
		echo "Upgraded Packages through Pacman."
	else
		echo "Packages not Upgraded"
    		exit 1
	fi	
}

# Upgrade AURs
upgrade_yay() {
	echo "Upgrade AUR Packages"

	yay -Syu

	if [ $? -eq 0 ]; then
		echo "Upgraded AUR packages with YAY."
	else
		echo "Packages not Upgraded"
    		exit 1
	fi
}

# Upgrade Pacman & Yay
main() {
	upgrade_pacman && upgrade_yay
}

# Run main
main
